In [1]:

ENV["PYTHON"] = "/home/jair/anaconda3/envs/rababa/bin/python"
import Pkg
Pkg.add("PyCall")
Pkg.build("PyCall")


    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`
    Building Conda ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/6cdc8832ba11c7695f494c9d9a1c31e90959ce0f/build.log`
    Building PyCall → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/71fd4022ecd0c6d20180e23ff1b3e05a143959c2/build.log`


In [2]:
#!pwd

In [2]:
#from hazm import *
using PyCall
hazm = pyimport("hazm")

PATH_HAZM = "resources/postagger.model"
PATH_FLEXICON = "resources/"

stemmer = hazm.Stemmer()
lemmatizer = hazm.Lemmatizer()
normalizer = hazm.Normalizer()
tagger = hazm.POSTagger(model=PATH_HAZM)
#openpyxl = pyimport("openpyxl")


PyObject <module 'hazm' from '/home/jair/anaconda3/envs/rababa/lib/python3.6/site-packages/hazm/__init__.py'>

In [3]:

PATH_HAZM = "resources/postagger.model"
PATH_FLEXICON = "resources/"

stemmer = hazm.Stemmer()
lemmatizer = hazm.Lemmatizer()
normalizer = hazm.Normalizer()
tagger = hazm.POSTagger(model=PATH_HAZM)


PyObject <hazm.POSTagger.POSTagger object at 0x7fcafa45e6d8>

In [17]:

dicCODE = Dict()

dicCODE["change all instances of ي and ك in the text to ی and ک"] = txt -> py"""normalise"""(txt)



#7 (generic function with 1 method)

In [14]:
str = "مزايایی"
txt = "مزايایی"

"مزايایی"

In [15]:
dicPYLIB["change all instances of ي and ك in the text to ی and ک"](txt)

"مزایایی"

In [15]:
string(text,text)

"مزاياییمزايایی"

In [8]:
hazm.word_tokenize(text)

1-element Vector{String}:
 "مزايایی"

In [9]:
tagger.tag(hazm.word_tokenize(text))

1-element Vector{Tuple{String, String}}:
 ("مزايایی", "N")

In [12]:
normalizer.normalize(text)

"مزایایی"

In [13]:
lemmatizer.lemmatize(text)

"مزايایی"

In [16]:
dicHAZM = Dict()

dicHAZM["pos"] = q -> Dict("HAZM" => string("pos ", q),
                           "data" => tagger.tag(hazm.word_tokenize(q))) 
dicHAZM["stem"] = q -> Dict("HAZM" => string("stem ", q),
                            "data" => stemmer.stem(q))
dicHAZM["lemma"] = q -> Dict("HAZM" => string("lemma ", q),
                             "data" => lemmatizer.lemmatize(q))

dicHAZM["normalize"] = q -> Dict("HAZM" => string("normalize ", q),
                                 "data" => normalizer.normalize(q))

#7 (generic function with 1 method)

In [10]:

# include("lib_julia/get_assets.jl")
include("lib/model.jl")


In [12]:
py"""normalise"""(txt)

"مزایایی"

In [15]:
tagger.tag(hazm.word_tokenize(str))

1-element Vector{Tuple{String, String}}:
 ("مزايایی", "N")

In [8]:
run(`pwd`)

/home/jair/WORK/HUMBABA/humbaba_interscript.jl/run/rababa


Process(`pwd`, ProcessExited(0))

In [11]:
run(`ls resources`)

Affixes.xlsx
data_trans.tar
df_data_2.csv
df_data.csv
Entries.xlsx
farsi_assets.pickle
poems_merged_trans.txt
poems_merged.txt
postagger.model
README.md
voa_persian_2003_2008_cleaned_trans.txt
voa_persian_2003_2008_cleaned.txt


Process(`ls resources`, ProcessExited(0))

In [19]:

using PyCall


py"""

from __future__ import unicode_literals
from hazm import *

import pandas as pd
import numpy as np
import _pickle as cPickle


LIB_LOCAL_PATH = '/home/jair/WORK/Farsi/rababa'

import sys

sys.path.append(LIB_LOCAL_PATH)


PATH_HAZM = "resources/postagger.model"

stemmer = Stemmer()
lemmatizer = Lemmatizer()
normalizer = Normalizer()
tagger = POSTagger(model=PATH_HAZM)


file = open('resources/farsi_assets.pickle','rb')
dic_assets = cPickle.load(file)
file.close()

df_Affixes = dic_assets['affixes']
df_Entries = dic_assets['entries']
d_FLEXI = dic_assets['d_FLEXI']
d_map_FLEXI = dic_assets['d_map_FLEXI']
d_HAZM = dic_assets['d_HAZM']
d_map_HAZM = dic_assets['d_map_HAZM']

"""

In [22]:
py"""dic_assets""" 

Dict{Any, Any} with 6 entries:
  "d_map_HAZM"  => Dict{Any, Any}("DETe"=>"Determiner", "CONJ"=>"Conjunction", …
  "d_FLEXI"     => Dict{Any, Any}("Conjunction"=>"C0, C1", "Punctuation"=>NaN, …
  "d_map_FLEXI" => Dict{Any, Any}("V3"=>"Verb", "N1"=>"Noun", "N6"=>"Pronoun", …
  "entries"     => PyObject       PhonologicalForm WrittenForm SynCatCode Freq …
  "d_HAZM"      => Dict{Any, Any}("Conjunction"=>"CONJ, CONJe", "Punctuation"=>…
  "affixes"     => PyObject       id Affix  ... هم‌نویسه با واحد واژگانی هجاسازی…

In [37]:
include("lib_julia/get_assets.jl")

In [38]:
py"""normalizer.normalize"""(text)

"مزایایی"

In [40]:
py"""normalise"""(text)

"مزایایی"

In [44]:
#wrd = text
#py"""process_noun"""(wrd)

In [32]:
py"""

a = 33
print(a*2)

def one():
    print(a)
"""

In [35]:
py"""
def one():
    return a
"""

In [36]:
py"""one"""()

33